variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:dind
    alias: docker

stages:
  - build
  - test

build:
  stage: build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:latest
  tags:
    - dind
  script:
    - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .

test:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:latest
  tags:
    - dind
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA echo "Tests passed"
