spring.application.name=sep-ba

spring.datasource.url=jdbc:postgresql://db:5432/sep
spring.datasource.username=sep
spring.datasource.password=sepsep123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

gemini.api.key=KEY
gemini.model=gemini-2.5-flash