spring.datasource.url=jdbc:postgresql://localhost:5432/sep
spring.application.name=sep-ba
spring.datasource.username=sep
spring.datasource.password=sepsep123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
